ViewRootImpl: Fix illegalStateException
Fixes an internal crash:

java.lang.illegalStateException: Requested window
android.view.ViewRootImpl$W@8604baa does not exist